##
# @description Services (customizations for development)
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the 
#              main/primary `docker-compose.yml`, i.e.:               
#              `docker compose \ 
#               -f docker-compose.yml \ 
#               -f docker-compose.dev.yml \
#               up -d`
# @note         Add file provider configuration to Traefik to be able to
#               use locally generated SSL certificates
# @note         Add PHP-FPM service that enables Xdebug feature
# @note         Add MailHog service to be able to work with emails locally
##
services:
  traefik:
    volumes:
      - ./services/traefik/etc:/etc/traefik
    environment:
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/file-provider

  fpm_xdebug:
    image:
      d3p1/magento-php:${BASE_PHP_VERSION}-fpm
    expose:
      - 9000
    volumes:
      - docroot:/app
    restart:
      always
    environment:
      - PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli opcache pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug
    labels:
      - traefik.enable=false
      
  mailhog:
    image: 
      d3p1/magento-mailhog:1.0
    expose:
      - 8025
      - 1025
    labels:
      - traefik.enable=false
      